name: wash-world-backend
include:
  - path: ./database.yaml
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 80:8000 # 0 - 1024 reserved. Use any port from 1025 to 65535
    volumes:
      - .:/app
    # Automatic rebuild
    develop:
      watch:
        - action: rebuild
          path: requirements.txt
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health').close()"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

