name: wash-world-frontend

services:
  react-app:
    build: 
      context: ..
      dockerfile: dev/Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
